### PR TITLE
finished vision_product_search_create_product_set

### PR DESCRIPTION
**Pull request by munkhuushmgl**

### CODE REVIEW

**Comment by beccasaurus** [comment]
Test? :)

**Review by beccasaurus — CHANGES_REQUESTED** [review]
Add a test please :)

**Comment by munkhuushmgl** [comment]
Working on it 😅, I will add as soon as I finish

**Comment by munkhuushmgl** [comment]
@beccasaurus I have added unit tests, ignore commit message Accidently typed "ls" for commit -m

**Comment by munkhuushmgl** [comment]
I have finished unit tests for CRUD --> product set [product_search]

Ignore my git commit message, I have accidentally put 'ls' instead my
intended message

Mike

**Comment by beccasaurus** [comment]
Looks good!

**Pull request closed without merging**
